version: "3"

services:
  agent:
    image: attacker
    container_name: attacker
    build:
      context: ../CyberLab/containers/caldera_agent/
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ../CyberLab/containers/caldera_agent/.env
    network_mode: host
  caldera:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "UTC" 
        WIN_BUILD: "true"
    environment:
      PUID: 1000
      PGID: 1000
    image: caldera:latest
    ports:
      - "8888:8888"
      - "8443:8443"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8853:8853"
      - "8022:8022"
      - "2222:2222"
    volumes:
      - ./:/usr/src/app
    command: --log DEBUG
