version: "3"

services:
  # caldera_agent:
  #   container_name: caldera_agent
  #   image: ghcr.io/uadelaide/caldera_agent:latest
  #   depends_on:
  #     - caldera_server
  #   restart: unless-stopped
  #   environment:
  #     TZ: "Australia/Adelaide"
  #     CALDERA_SERVER: "http://localhost:8888/weather"
  #     RL_AGENT_URL: "http://192.168.32.33:30902/api/attacker"
  #     LOG_LEVEL: "INFO"
  #   network_mode: host
  caldera_server:
    container_name: caldera_server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "UTC" 
        WIN_BUILD: "true"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    image: caldera:latest
    ports:
      - "8888:8888"
      - "8443:8443"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8853:8853"
      - "8022:8022"
      - "2222:2222"
    volumes:
      - ./:/usr/src/app
    command: --log INFO
